print(type(str(6.76)))
print(type(str(2)))
print(type(str(67)))
print(type(str(6.75)))
print(type(str(3)))

print(type(int(3.98)))
print(type(int("3")))
print(type(int(6)))
print(type(int(32.99)))
print(type(int("45")))

print(type(float("4")))
print(type(float(67)))
print(type(float("59")))
print(type(float(5.89)))
print(type(float("90.9")))

num1=input("please enter number 1: ")
num2=input("please enter number 2: ")
num3=input("please enter number 3: ")
num4=input("please enter number 4: ")
num5=input("please enter number 5: ")

print(str(num1 + num2 + num3 + num4 + num5))
print((num1 * int(num2) * int(num3) * int(num4) * int(num5)))
print((int(num1) - int(num2) - int(num3) - int(num4) - int(num5)))
print((int(num1) / int(num2) / int(num3) / int(num4) / int(num5)))
print((int(num1) // int(num2) //int(num3) // int(num4) // int(num5)))
print((int(num1) % int(num2) % int(num3) % int(num4) % int(num5)))
